### ISSUE TITLE
Diagram Generation Does Not Correctly Recognize Type Variables

### ISSUE THREAD

**Issue by syoon2** [Reithger/Project-Diagram-Generator#11]
## Description
If a method has a type variable declared, the generated diagram gives incorrect return type for that method.

## Steps to Reproduce
1. Create an empty directory and add `Demo.java` as shown below.
```java
public class Demo {
    public static <T> void meaningless(T obj) {
        return;
    }
}
```
2. Select the directory with `Demo.java` in diagram generator.
3. Toggle `Show Functions?` checkbox then generate diagram.
4. Observe the generated diagram.

### Expected Behavior
Generated diagram reports return type of `meaningless()` as `void`.

### Actual Behavior
Generated diagram reports return type of `meaningless()` as `<T>`.
![demo](https://user-images.githubusercontent.com/55358516/201431374-38b9e8f9-4af9-4105-bd8f-3da3604a4977.jpg)

**Comment by syoon2** [comment]
Here's another code that generates incorrect return type:
```java
public class Demo {
    public <T extends Comparable<T>> void meaningless(T obj) {
        obj.compareTo(obj);
        return;
    }
}
```
![demo](https://user-images.githubusercontent.com/55358516/201432048-15fd596a-58e5-40b7-89f5-8431207b51c9.jpg)

**Comment by Reithger** [comment]
New update should fix that, let me know if it doesn't
