### ISSUE TITLE
Diagram Generation Does Not Correctly Recognize Keyword `final`

### ISSUE THREAD

**Issue by syoon2** [Reithger/Project-Diagram-Generator#12]
Possibly related to #11 

## Code to reproduce issue

```java
public class Demo {
    public final void meaningless(Object obj) {
        obj.toString();
        return;
    }
}
```

### Expected Behavior

Return type of `void` is correctly recognized

### Actual Behavior

![demo](https://user-images.githubusercontent.com/55358516/201531404-25024d60-67b5-4b6d-b732-5019f3ad3aba.jpg)

**Comment by syoon2** [comment]
Neither `final` variables nor constants (`static final`) get displayed with the generator - indicating some issue with processing of keyword `final`.

**Comment by Reithger** [comment]
Error should be fixed in newest version, let me know if it doesn't
