### ISSUE TITLE
'Packages to Ignore' Popup Cannot Scroll Properly

### ISSUE THREAD

**Issue by syoon2** [Reithger/Project-Diagram-Generator#14]
When running the generator on a multi-package project, the popup cannot scroll properly to display all the available packages. The scrollbar seems to be moving, but the list of packages does not scroll with it.

**Comment by Reithger** [comment]
Fixed it, was a weird mis-use of element categories with a scrollbar, not sure when I changed something to cause that to break. Isn't bounded on either end, but that's a graphics library issue I'll need to look into.
Pushed that update already.
