### ISSUE TITLE
`final` Fields Not Displayed

### ISSUE THREAD

**Issue by syoon2** [Reithger/Project-Diagram-Generator#16]
> Neither `final` variables nor constants (`static final`) get displayed with the generator - indicating some issue with processing of keyword `final`.
>
> _Originally posted by @syoon2 in https://github.com/Reithger/Project-Diagram-Generator/issues/12#issuecomment-1314406517_
      

No field declared as `final` gets included in the generated diagram. This includes both `final` instance variables and constants (i.e., `static final` fields).

**Comment by Reithger** [comment]
It isn't common practice to show constant values in a UML; I can jury rig it a bit to denote a variable is final, though. The diagram is illustrative of the project, doesn't have to abide by conventions.

**Comment by Reithger** [comment]
Cool, added final detection and made a fourth decision-variable for whether you want to see those or not. Updated the headless mode to encompass that as well, but did not update the help guide whoops I'll go do that. Should be fixed now, though, didn't see any errors on my end from some quick testing.
