### ISSUE TITLE
Feature request: Attempt to Automatically Locate `dot` executable

### ISSUE THREAD

**Issue by syoon2** [Reithger/Project-Diagram-Generator#4]
It would be quite useful to automate (or at least attempt to automate) the process of finding the `dot` executable without asking user - possibly opening room for headless deployment in automated environments.

**Comment by Reithger** [comment]
Might be able to do something like that, but I think I ran into issues of being able to freely explore the user's file system from an arbitrary position where the project is being run from. It should be 'do it once and forget', though I've been toying with embedding GraphViz in the project itself which I should get back to so we can avoid this entirely.

**Comment by syoon2** [comment]
I think that (well, at least in *NIX environment) that attempting to find `dot` executable from the system's `PATH` environment variable would be a safe bet to make.
Since I intend to run this in an automated, noninteractive environment, e.g., GitHub Actions or Azure Pipelines, "do it once" part of "do it once and forget" is not really an option - and this is where this automated attempt would come in.

**Comment by syoon2** [comment]
>I've been toying with embedding GraphViz in the project itself which I should get back to so we can avoid this entirely.

Maybe you could consider replacing [`GraphViz.java`](https://github.com/Reithger/Project-Diagram-Generator/blob/main/src/image/GraphViz.java) with [graphviz-java](https://github.com/nidi3/graphviz-java) library? Seems like (from quickly glancing over README there... at least) it comes with automatic locating of `dot` executable.
