### ISSUE TITLE
Feature Request: Headless Mode

### ISSUE THREAD

**Issue by syoon2** [Reithger/Project-Diagram-Generator#7]
Currently this program only supports interactive mode (via GUI) - having a headless mode implemented would make noninteractive runs of this program way smoother.

Depends on #4

**Comment by Reithger** [comment]
You can run the program from 'Main.java' and change 'runReal()' for 'runLoose(["path to project"], "[output image name]", "package to ignore in making UML", "another package to ignore in making UML", "I used var args so just keep going")'. Is that good or do you need more to satisfy a headless mode? Unfamiliar with the term in specificity.

**Comment by syoon2** [comment]
For the purpose of avoiding hardcoding in general, I'd want something like this:
- passing in 0 cmd line arg runs generator in GUI mode, i.e., `runReal()`
- passing in $>1$ cmd line args runs headless mode, i.e., `runLoose()`, using cmd line args as arguments for `runLoose()`.

Rough sketch of this idea is available in #9 - although obviously it would need more work (why this PR is a draft!).

To add on top of this, as I intend to deploy the headless mode of this project in cloud-hosted pipelines (that I have which directory I will be using), having _a priori_ knowledge of the source code path is not really an option.
